module.exports = {
	BOOK: 'BOOK',
	BOOK_SUCCESS: 'BOOK_SUCCESS',
	BOOK_ERROR: 'BOOK_ERROR',

	PRE_CANCEL: 'PRE_CANCEL',
	PRE_CANCEL_SUCCESS: 'PRE_CANCEL_SUCCESS',
	PRE_CANCEL_ERROR: 'PRE_CANCEL_ERROR',

	CANCEL: 'CANCEL',
	CANCEL_SUCCESS: 'CANCEL_SUCCESS',
	CANCEL_ERROR: 'CANCEL_ERROR'
};
