module.exports = {
    GET_PROPERTY: 'GET_PROPERTY',
    GET_PROPERTY_SUCCESS: 'GET_PROPERTY_SUCCESS',
    GET_PROPERTY_ERROR: 'GET_PROPERTY_ERROR',

    GET_PROPERTY_DETAILS: 'GET_PROPERTY_DETAILS',
    GET_PROPERTY_DETAILS_SUCCESS: 'GET_PROPERTY_DETAILS_SUCCESS',
    GET_PROPERTY_DETAILS_ERROR: 'GET_PROPERTY_DETAILS_ERROR',

    GET_AUTOCOMPLETE_PROPERTIES: 'GET_AUTOCOMPLETE_PROPERTIES',
	GET_AUTOCOMPLETE_PROPERTIES_SUCCESS: 'GET_AUTOCOMPLETE_PROPERTIES_SUCCESS',
	GET_AUTOCOMPLETE_PROPERTIES_ERROR: 'GET_AUTOCOMPLETE_PROPERTIES_ERROR',

	GET_PROVIDER_SEARCH: 'GET_PROVIDER_SEARCH',
    GET_PROVIDER_SEARCH_SUCCESS: 'GET_PROVIDER_SEARCH_SUCCESS',
    GET_PROVIDER_SEARCH_ERROR: 'GET_PROVIDER_SEARCH_ERROR',

    GET_PREBOOK_SUCCESS: 'GET_PREBOOK_SUCCESS',
    GET_PREBOOK_ERROR: 'GET_PREBOOK_ERROR',

	GET_PROVIDERS: 'GET_PROVIDERS',
    GET_PROVIDERS_SUCCESS: 'GET_PROVIDER_SUCCESS',
    GET_PROVIDERS_ERROR: 'GET_PROVIDER_ERROR',

    POST_PREBOOK: 'POST_PREBOOK',
    POST_PREBOOK_SUCCESS: 'GET_PROVIDER_SUCCESS',
    POST_PREBOOK_ERROR: 'GET_PROVIDER_ERROR'
};
